default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: root
  redis:
    host: localhost
    port: 6379
    db: 0
    options:
      namespace: saiyan-dev

development:
  <<: *default
  database: saiyan_development

test:
  <<: *default
  database: saiyan_test

production:
  <<: *default
  database: saiyan_production
