default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: root

development:
  <<: *default
  database: saiyan_development

test:
  <<: *default
  database: saiyan_test

production:
  <<: *default
  database: saiyan_production
